=== world464/deklarativeProgrammierung/src/a2/rechnungensBeschreibung.dtd
<!ELEMENT rechnungen (rechnung+) >
<!ELEMENT rechnung (absender, empfaenger, leistungen, daten)>

<!ELEMENT absender (name, adresse, kontakt?)>
<!ELEMENT empfaenger (name, adresse, kontakt?)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT adresse (strasse, haus-nummer, postleitzahl, ort)>

<!ELEMENT strasse (#PCDATA)>
<!ELEMENT haus-nummer (#PCDATA)>
<!ELEMENT postleitzahl (#PCDATA)>
<!ELEMENT ort (#PCDATA)>

<!ELEMENT kontakt (telefon?, fax?, email?)>

<!ELEMENT telefon (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT leistungen (leistung+)>
<!ELEMENT leistung (menge?, produkt, einzel-preis, gesamt-preis, mehr-wert-steuer)>

<!ELEMENT menge (#PCDATA) >
<!ELEMENT produkt (#PCDATA) >
<!ELEMENT einzel-preis (#PCDATA) >
<!ATTLIST einzel-preis waehrung CDATA #REQUIRED>
<!ELEMENT gesamt-preis (#PCDATA) >
<!ATTLIST gesamt-preis waehrung CDATA #REQUIRED>
<!ELEMENT mehr-wert-steuer (#PCDATA) >

<!ELEMENT daten (steuer-nummer, ausstellungs-datum, rechnungs-nummer, abrechnung) >

<!ELEMENT steuer-nummer (#PCDATA) >
<!ELEMENT ausstellungs-datum (#PCDATA) >
<!ELEMENT rechnungs-nummer (#PCDATA) >

<!ELEMENT abrechnung (betrag, netto, mehr-wert-steuer-gesamt) >

<!ELEMENT betrag (#PCDATA) >
<!ATTLIST betrag waehrung CDATA #REQUIRED>
<!ELEMENT netto (#PCDATA) >
<!ATTLIST netto waehrung CDATA #REQUIRED>
<!ELEMENT mehr-wert-steuer-gesamt (#PCDATA) >
<!ATTLIST mehr-wert-steuer-gesamt waehrung CDATA #REQUIRED>

=== world464/deklarativeProgrammierung/src/a2/rechnungen2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rechnungen SYSTEM "rechnungensBeschreibung.dtd">
<rechnungen><!-- Mat: 82356 Gruppe 0 -->
	<rechnung>
		<absender>
			<name>Rochade-La Hoff Pharma GmbH</name>
			<adresse>
				<strasse>An der Chemie</strasse>
				<haus-nummer>17</haus-nummer>
				<postleitzahl>79639</postleitzahl>
				<ort>Grenzych-Wahlen</ort>
			</adresse>
			<kontakt>
				<telefon>07624/666333999</telefon>
				<fax>07624/666333990</fax>
			</kontakt>
		</absender>
		<empfaenger>
			<name>Dr.med.Cyprian Zottel</name>
			<adresse>
				<strasse>Soddelstrudel</strasse>
				<haus-nummer>5a</haus-nummer>
				<postleitzahl>13023</postleitzahl>
				<ort>Zotenheim</ort>
			</adresse>
		</empfaenger>
		<leistungen>
			<leistung>
				<menge>3 Packungen</menge>
				<produkt>Grippemittel"Tumifla"</produkt>
				<einzel-preis waehrung="Euro">120.00</einzel-preis>
				<gesamt-preis waehrung="Euro">360.00</gesamt-preis>
				<mehr-wert-steuer>19</mehr-wert-steuer>
			</leistung>
			<leistung>
				<menge></menge>
				<produkt>Beratung pauschal</produkt>
				<einzel-preis waehrung="Euro"></einzel-preis>
				<gesamt-preis waehrung="Euro">50.00</gesamt-preis>
				<mehr-wert-steuer>19</mehr-wert-steuer>
			</leistung>
			<leistung>
				<menge>2 Liter</menge>
				<produkt>Abführmittel"Wech damit" pro Liter</produkt>
				<einzel-preis waehrung="Euro">99.99</einzel-preis>
				<gesamt-preis waehrung="Euro">199.98</gesamt-preis>
				<mehr-wert-steuer>19</mehr-wert-steuer>
			</leistung>
			<leistung>
				<menge>2 Stück</menge>
				<produkt>Energieriegel "Satto"</produkt>
				<einzel-preis waehrung="Euro">5.98</einzel-preis>
				<gesamt-preis waehrung="Euro">11.96</gesamt-preis>
				<mehr-wert-steuer>7</mehr-wert-steuer>
			</leistung>
		</leistungen>
		<daten>
			<steuer-nummer>DE333666999</steuer-nummer>
			<ausstellungs-datum>2017-08-08</ausstellungs-datum>
			<rechnungs-nummer>98-798-7987</rechnungs-nummer>
			<abrechnung>
				<betrag waehrung="Euro">962.22</betrag>
				<netto waehrung="Euro">490.22</netto>
				<mehr-wert-steuer-gesamt waehrung="Euro">116.74</mehr-wert-steuer-gesamt>
			</abrechnung>
		</daten>
	</rechnung>
</rechnungen>
